# Generated by Terraform — do not edit manually
[application]
name       = ${app_name}
env        = ${environment}
port       = ${port}
log_level  = ${log_level}

[server]
host       = 0.0.0.0
timeout    = 30

[logging]
format     = json
output     = stdout
