apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: devops
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900
